#pragma once

#include <algorithm>
#include <cerrno>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <cwchar>
#include <cwctype>
#include <iterator>
#include <list>
#include <memory>
#include <new>
#include <set>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include <comutil.h>
#include <io.h>
#include <msxml6.h>
#include <shlwapi.h>
#include <strsafe.h>
#include <wil/result.h>

#include <mrm/common/Base.h>
#include <mrm/BaseInternal.h>
#include <mrm/common/BaseInternal.h>
#include <mrm/common/file/FileBase.h>
#include <mrm/common/file/MrmFiles.h>
#include <mrm/common/MrmProfileData.h>
#include <mrm/DefObject.h>
#include <mrm/Results.h>
#include <mrm/Atoms.h>
#include <mrm/Collections.h>
#include <mrm/Checksums.h>
#include <mrm/MrmQualifiers.h>
#include <mrm/MrmEnvironment.h>
#include <mrm/platform/base.h>
#include <mrm/readers/MrmManagers.h>
#include <mrm/readers/MrmReaders.h>
#include <mrm/build/MrmBuilders.h>
#include <mrmmin/BlobResult.h>
#include <mrmmin/StringResult.h>

#include <XmlUtil.h>
#include <CFolderIndexer.h>
#include <CPriFileIndexer.h>
#include <CPriInfoIndexer.h>
#include <CResFilesIndexer.h>
#include <CResJsonIndexer.h>
#include <CResxIndexer.h>
#include <CEmbedFilesIndexer.h>
#include <IndexerBase.h>
#include <ItemInstanceSink.h>
#include <SchemaReader.h>
#include <QualifierApplicator.h>
#include <XmlHelper.h>
#include <IFsIndexer.h>
#include <IIndexOptions.h>
#include <LogSink.h>
#include <ClientProfileBase.h>
#include <DynamicArray.h>
#include <DefStatus.h>
#include <Bcp47.h>
#include <Language.h>
