#if __has_include_next(<winerror.h>)
#include_next <winerror.h>

#ifndef ERROR_MRM_UNSUPPORTED_FILE_TYPE_FOR_MERGE
#define ERROR_MRM_UNSUPPORTED_FILE_TYPE_FOR_MERGE 15141L
#endif

#ifndef ERROR_MRM_UNSUPPORTED_FILE_TYPE_FOR_LOAD_UNLOAD_PRI_FILE
#define ERROR_MRM_UNSUPPORTED_FILE_TYPE_FOR_LOAD_UNLOAD_PRI_FILE 15142L
#endif

#ifndef ERROR_PRI_MERGE_VERSION_MISMATCH
#define ERROR_PRI_MERGE_VERSION_MISMATCH 15148L
#endif

#ifndef ERROR_PRI_MERGE_MISSING_SCHEMA
#define ERROR_PRI_MERGE_MISSING_SCHEMA 15149L
#endif

#ifndef ERROR_PRI_MERGE_LOAD_FILE_FAILED
#define ERROR_PRI_MERGE_LOAD_FILE_FAILED 15150L
#endif

#ifndef ERROR_PRI_MERGE_ADD_FILE_FAILED
#define ERROR_PRI_MERGE_ADD_FILE_FAILED 15151L
#endif

#ifndef ERROR_PRI_MERGE_WRITE_FILE_FAILED
#define ERROR_PRI_MERGE_WRITE_FILE_FAILED 15152L
#endif

#ifndef ERROR_PRI_MERGE_MULTIPLE_PACKAGE_FAMILIES_NOT_ALLOWED
#define ERROR_PRI_MERGE_MULTIPLE_PACKAGE_FAMILIES_NOT_ALLOWED 15153L
#endif

#ifndef ERROR_PRI_MERGE_MULTIPLE_MAIN_PACKAGES_NOT_ALLOWED
#define ERROR_PRI_MERGE_MULTIPLE_MAIN_PACKAGES_NOT_ALLOWED 15154L
#endif

#ifndef ERROR_PRI_MERGE_BUNDLE_PACKAGES_NOT_ALLOWED
#define ERROR_PRI_MERGE_BUNDLE_PACKAGES_NOT_ALLOWED 15155L
#endif

#ifndef ERROR_PRI_MERGE_MAIN_PACKAGE_REQUIRED
#define ERROR_PRI_MERGE_MAIN_PACKAGE_REQUIRED 15156L
#endif

#ifndef ERROR_PRI_MERGE_RESOURCE_PACKAGE_REQUIRED
#define ERROR_PRI_MERGE_RESOURCE_PACKAGE_REQUIRED 15157L
#endif

#ifndef ERROR_MRM_PACKAGE_NOT_FOUND
#define ERROR_MRM_PACKAGE_NOT_FOUND 15159L
#endif

#ifndef ERROR_MRM_MISSING_DEFAULT_LANGUAGE
#define ERROR_MRM_MISSING_DEFAULT_LANGUAGE 15160L
#endif

#ifndef ERROR_MRM_SCOPE_ITEM_CONFLICT
#define ERROR_MRM_SCOPE_ITEM_CONFLICT 15161L
#endif

#else

#pragma once

#include <winnt.h>

#define SUCCEEDED(result) (static_cast<HRESULT>(result) >= 0)
#define FAILED(result) (static_cast<HRESULT>(result) < 0)
#define MAKE_HRESULT(severity, facility, code) \
    static_cast<HRESULT>((static_cast<ULONG>(severity) << 31) | (static_cast<ULONG>(facility) << 16) | static_cast<ULONG>(code))
#define HRESULT_CODE(result) (static_cast<ULONG>(result) & 0xffff)
#define HRESULT_FACILITY(result) ((static_cast<ULONG>(result) >> 16) & 0x1fff)
#define __HRESULT_FROM_WIN32(error) \
    (static_cast<HRESULT>(error) <= 0 ? static_cast<HRESULT>(error) : \
                                        static_cast<HRESULT>((static_cast<ULONG>(error) & 0xffff) | 0x80070000UL))
#define HRESULT_FROM_WIN32(error) __HRESULT_FROM_WIN32(error)
#define HRESULT_FROM_NT(status) static_cast<HRESULT>(static_cast<ULONG>(status) | FACILITY_NT_BIT)

#define FACILITY_NT_BIT 0x10000000
#define FACILITY_WIN32 7
#define FACILITY_SSPI 9

#define S_OK static_cast<HRESULT>(0x00000000)
#define S_FALSE static_cast<HRESULT>(0x00000001)
#define E_UNEXPECTED static_cast<HRESULT>(0x8000FFFFUL)
#define E_NOTIMPL static_cast<HRESULT>(0x80004001UL)
#define E_OUTOFMEMORY static_cast<HRESULT>(0x8007000EUL)
#define E_INVALIDARG static_cast<HRESULT>(0x80070057UL)
#define E_NOINTERFACE static_cast<HRESULT>(0x80004002UL)
#define E_POINTER static_cast<HRESULT>(0x80004003UL)
#define E_HANDLE static_cast<HRESULT>(0x80070006UL)
#define E_ABORT static_cast<HRESULT>(0x80004004UL)
#define E_FAIL static_cast<HRESULT>(0x80004005UL)
#define E_ACCESSDENIED static_cast<HRESULT>(0x80070005UL)
#define CLASS_E_CLASSNOTAVAILABLE static_cast<HRESULT>(0x80040111UL)
#define STG_E_INVALIDPOINTER static_cast<HRESULT>(0x80030009UL)
#define STG_E_WRITEFAULT static_cast<HRESULT>(0x8003001dUL)

#define ERROR_SUCCESS 0L
#define ERROR_INVALID_FUNCTION 1L
#define ERROR_FILE_NOT_FOUND 2L
#define ERROR_PATH_NOT_FOUND 3L
#define ERROR_ACCESS_DENIED 5L
#define ERROR_INVALID_HANDLE 6L
#define ERROR_NOT_ENOUGH_MEMORY 8L
#define ERROR_BAD_FORMAT 11L
#define ERROR_INVALID_DATA 13L
#define ERROR_NO_MORE_FILES 18L
#define ERROR_NOT_READY 21L
#define ERROR_INVALID_PARAMETER 87L
#define ERROR_PROC_NOT_FOUND 127L
#define ERROR_DISK_FULL 112L
#define ERROR_INSUFFICIENT_BUFFER 122L
#define ERROR_INVALID_NAME 123L
#define ERROR_MOD_NOT_FOUND 126L
#define ERROR_BAD_PATHNAME 161L
#define ERROR_BAD_ENVIRONMENT 10L
#define ERROR_ALREADY_EXISTS 183L
#define ERROR_MORE_DATA 234L
#define ERROR_NO_DATA 232L
#define ERROR_NO_MORE_ITEMS 259L
#define ERROR_MR_MID_NOT_FOUND 317L
#define ERROR_INVALID_ADDRESS 487L
#define ERROR_ARITHMETIC_OVERFLOW 534L
#define ERROR_UNHANDLED_EXCEPTION 574L
#define ERROR_ILLEGAL_CHARACTER 582L
#define ERROR_UNDEFINED_CHARACTER 583L
#define ERROR_NO_MORE_MATCHES 626L
#define ERROR_RANGE_NOT_FOUND 644L
#define ERROR_OLD_WIN_VERSION 1150L
#define ERROR_NO_UNICODE_TRANSLATION 1113L
#define ERROR_NOT_FOUND 1168L
#define ERROR_NO_MATCH 1169L
#define ERROR_IMPLEMENTATION_LIMIT 1292L
#define ERROR_INTERNAL_ERROR 1359L
#define ERROR_INVALID_INDEX 1413L
#define ERROR_XML_PARSE_ERROR 1465L
#define ERROR_CANT_ACCESS_FILE 1920L
#define ERROR_FILE_TOO_LARGE 223L
#define ERROR_DUPLICATE_TAG 2014L
#define ERROR_INVALID_OPERATION 4317L
#define ERROR_INVALID_STATE 5023L
#define APPMODEL_ERROR_NO_PACKAGE 15700L

#define ERROR_MRM_RUNTIME_NO_DEFAULT_OR_NEUTRAL_RESOURCE 15110L
#define ERROR_MRM_INVALID_FILE_TYPE 15112L
#define ERROR_MRM_UNKNOWN_QUALIFIER 15113L
#define ERROR_MRM_INVALID_QUALIFIER_VALUE 15114L
#define ERROR_MRM_NO_CANDIDATE 15115L
#define ERROR_MRM_NO_MATCH_OR_DEFAULT_CANDIDATE 15116L
#define ERROR_MRM_RESOURCE_TYPE_MISMATCH 15117L
#define ERROR_MRM_DUPLICATE_MAP_NAME 15118L
#define ERROR_MRM_DUPLICATE_ENTRY 15119L
#define ERROR_MRM_INVALID_PRI_FILE 15126L
#define ERROR_MRM_NAMED_RESOURCE_NOT_FOUND 15127L
#define ERROR_MRM_MAP_NOT_FOUND 15135L
#define ERROR_MRM_UNSUPPORTED_PROFILE_TYPE 15136L
#define ERROR_MRM_INVALID_QUALIFIER_OPERATOR 15137L
#define ERROR_MRM_TOO_MANY_RESOURCES 15140L
#define ERROR_MRM_UNSUPPORTED_FILE_TYPE_FOR_MERGE 15141L
#define ERROR_MRM_UNSUPPORTED_FILE_TYPE_FOR_LOAD_UNLOAD_PRI_FILE 15142L
#define ERROR_PRI_MERGE_VERSION_MISMATCH 15148L
#define ERROR_PRI_MERGE_MISSING_SCHEMA 15149L
#define ERROR_PRI_MERGE_LOAD_FILE_FAILED 15150L
#define ERROR_PRI_MERGE_ADD_FILE_FAILED 15151L
#define ERROR_PRI_MERGE_WRITE_FILE_FAILED 15152L
#define ERROR_PRI_MERGE_MULTIPLE_PACKAGE_FAMILIES_NOT_ALLOWED 15153L
#define ERROR_PRI_MERGE_MULTIPLE_MAIN_PACKAGES_NOT_ALLOWED 15154L
#define ERROR_PRI_MERGE_BUNDLE_PACKAGES_NOT_ALLOWED 15155L
#define ERROR_PRI_MERGE_MAIN_PACKAGE_REQUIRED 15156L
#define ERROR_PRI_MERGE_RESOURCE_PACKAGE_REQUIRED 15157L
#define ERROR_MRM_PACKAGE_NOT_FOUND 15159L
#define ERROR_MRM_MISSING_DEFAULT_LANGUAGE 15160L
#define ERROR_MRM_SCOPE_ITEM_CONFLICT 15161L

#define NTE_BAD_SIGNATURE static_cast<HRESULT>(0x80090006U)
#define NTE_EXISTS static_cast<HRESULT>(0x8009000FU)

#endif // __has_include_next(<winerror.h>)
